// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

// LOGOUT
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

// login_chack
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_GET_STATUS_VALUE = "AUTH_GET_STATUS_VALUE";

//basic_search
export const BASIC_SEARCH = "BASIC_SEARCH";
export const BASIC_SEARCH_SUCCESS = "BASIC_SEARCH_SUCCESS";
export const BASIC_SEARCH_FAILURE = "BASIC_SEARCH_FAILURE";

export const DETAIL_SEARCH = "DETAIL_SEARCH";
export const DETAIL_SEARCH_SUCCESS = "DETAIL_SEARCH_SUCCESS";
export const DETAIL_SEARCH_FAILURE = "DETAIL_SEARCH_FAILURE";

//naver search
export const NAVER_SEARCH = "NAVER_SEARCH";
export const NAVER_SEARCH_SUCCESS = "NAVER_SEARCH_SUCCESS";
export const NAVER_SEARCH_FAILURE = "NAVER_SEARCH_FAILURE";


export const ADD_LIST = "ADD_LIST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const ADD_LIST_FAILURE = "ADD_LIST_FAILURE";

export const REMOVE_LIST = "REMOVE_LIST";
export const REMOVE_LIST_SUCCESS = "REMOVE_LIST_SUCCESS";
export const REMOVE_LIST_FAILURE = "REMOVE_LIST_FAILURE";

export const GET_PLACELIST = "GET_PLACELIST";
export const GET_PLACELIST_SUCCESS = "GET_PLACELIST_SUCCESS";
export const GET_PLACELIST_FAILURE = "GET_PLACELIST_FAILURE";