// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

// LOGOUT
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

// checkToken
export const CHECK_TOKEN = "CHECK_TOKEN";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

//SIGN_OUT
export const SIGN_OUT = "SIGN_OUT";


//GET_MY_LIST
export const GET_MY_LIST = "GET_MY_LIST";
export const GET_MY_LIST_SUCCESS = "GET_MY_LIST_SUCCESS";
export const GET_MY_LIST_FAILURE = "GET_MY_LIST_FAILURE";